branches:
  only:
    - master

language: php

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python-sqlalchemy python-mysqldb python-twisted-web python-ldap python-gobject xsltproc docbook-xsl

install: sh -c ' cd core && sh autogen.sh && ./configure && make && sudo make install &&  cd ../pulse2 && sh autogen.sh && ./configure && make && sudo make install '

notifications:
  email:
    recipients:
      - nicolas.lecureuil@siveo.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc01.siveo.net#main"
    on_success: always #|never|change] # default: always
    on_failure: always #|never|change] # default: always
    use_notice: true
